learning_log/urls.py
from django.contrib import admin
from django.urls import path,include
# from django.conf.urls import include, url

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',include('pizzas.urls',namespace='pizzas')),
    path('',include('learning_logs.urls',namespace='learning_logs')),
]

learning_logs/urls.py
# coding:utf-8
# @Time    :  2020-06-22 18:20
# @Author  : Administrator
# @File    : learning_log
# @Description : 
"""定义learning_logs的URL模式"""
from django.conf.urls import url
from django.urls import path,re_path,include
from . import views
urlpatterns = [
    # 主页
    # url(r'^$', views.index, name='index'),
    # path('',views.index),
    re_path('^$', views.index, name='index'),
    # 显示所有主题
    path('topics/', views.topics,name='topics'),
    # 特定主题的详细页面
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    path('hd/', views.add_user, name='topics'),
]

app_name = 'learning_logs'

pizzas/urls.py
# coding:utf-8
# @Time    :  2020-06-23 16:27
# @Author  : Administrator
# @File    : learning_log
# @Description :
from django.conf.urls import url
from django.urls import path,re_path,include
from . import views
urlpatterns = [
    # 主页
    # url(r'^$', views.index, name='index'),
    # path('',views.index),
    re_path('^$', views.index, name='index'),
    # 显示所有披萨
    path('pizza/', views.pizzas,name='pizzas'),
    # 披萨的配料
    url(r'^pizza/(?P<pizza_id>\d+)/$', views.pizza, name='pizza'),
]

app_name = 'pizzas'

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    '''用户学习的主题'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""

        return self.text[:50] + "..."

class UserInfo(models.Model):
    user_id = models.CharField("user id ",max_length=4,primary_key=True)
    user_name = models.CharField("user name",max_length=10)
    password = models.CharField("password",max_length=10)
    status = models.CharField("user status 有效/无效",default=1,max_length=5)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    '''pizza的name'''
    name = models.CharField(max_length=200)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.name

class Topping(models.Model):
    """配料"""
    pizza = models.ForeignKey(Pizza,on_delete=models.CASCADE)
    name = models.TextField()

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""

        return self.name[:50] + "..."

learning_logs/forms.py
# -*- coding: utf-8 -*-
# @Time    : 2020/6/23 23:09:26
# @Author  : handong
# @FileName: forms.py
# @Software: PyCharm

from django import forms
from.models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic,UserInfo
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .forms import TopicForm,EntryForm
import json
from django.views.decorators.csrf import csrf_exempt






# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    '''显示所有主题'''
    topics = Topic.objects.order_by('date_added')
    context = {'topics':topics}
    return render(request,  'learning_logs/topics.html', context)

def topic(request, topic_id):
    '''显示单个主题及其所有条目'''
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
    # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据,对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request,topic_id):
    """添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
    # 未提交数据：创建一个新表单
        form = EntryForm()
    else:
        # POST提交的数据,对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

#新增用户
@csrf_exempt
def add_user(request):
    if request.method == "POST":
        req = json.loads(request.body)
        print(req)
        user_id = req["user_id"]
        user_name = req["user_name"]
        password = req["password"]
        status = req["status"]
        user_exist = UserInfo.objects.filter(user_id=user_id)
        if len(user_exist) != 0:
            return JsonResponse({"status": "BS.400", "msg": "user aleady exist,fail to publish."})
        add_art = UserInfo(user_id=user_id, user_name=user_name,password=password, status="1")
        add_art.save()
        return 'add user success'

pizzas/views.py
from django.shortcuts import render
from .models import Pizza
# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    '''显示所有主题'''
    pizzas = Pizza.objects.all()
    context = {'pizzas':pizzas}
    return render(request,  'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    '''显示单个主题及其所有条目'''
    pizza = Pizza.objects.get(id=pizza_id)
    entries = pizza.topping_set.all()
    context = {'pizza': pizza, 'topping': entries}
    return render(request, 'pizzas/pizza.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
<p>
  {% block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
{% extends "learning_logs/base.html" %}
{% block content %}
   <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  <p>Add a new entry:</p>
   <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
   </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
{% extends "learning_logs/base.html" %}

{% block content %}
 <p>Add a new topic:</p>

 <form action="{% url 'learning_logs:new_topic' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">add topic</button>
 </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p>Topic: {{ topic }}</p>

  <p>Entries:</p>
  <p>
      <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>

    <ul>
    {% for entry in entries %}
        <li><p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
          <p>{{ entry.text|linebreaks }}</p>
        </li>
       {% empty %}
        <li>
            There are no entries for this topic yet.
        </li>
    {% endfor %}
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>Topics</p>

    <ul>
      {% for topic in topics %}
        <li>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </li>
      {% empty %}
        <li>No topics have been added yet.</li>
      {% endfor %}
    </ul>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
{% endblock content %}

pizzas/templates/pizzas/base.html
<!DOCTYPE html>
<p>
    <a href="{% url 'pizzas:index' %}">Dining room</a> -
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
<p>
  {% block content %}{% endblock content %}

pizzas/templates/pizzas/index.html
<!DOCTYPE html>
{% extends "pizzas/base.html" %}

{% block content %}
  <p>hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh</p>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
<!DOCTYPE html>
{% extends 'pizzas/base.html' %}

{% block content %}

    <p>Pizza: {{ pizza }}</p>

  <p>Topping:</p>
   <ul>
    {% for topping in entries %}
        <li>
          <p>{{ topping.text|linebreaks }}</p>
        </li>
    {% empty %}
        <li>
            There are no entries for this topic yet.
        </li>
    {% endfor %}
   </ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
<!DOCTYPE html>
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Pizzas</p>

    <ul>
      {% for pizza in pizzas %}
        <li>
          <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
        </li>
      {% empty %}
        <li>No topics have been added yet.</li>
      {% endfor %}
    </ul>
{% endblock content %}